# Generated by Django 4.1 on 2024-05-03 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0003_transaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='sub_category',
            field=models.CharField(default='', max_length=100),
        ),
    ]
