# Generated by Django 4.1 on 2024-05-04 08:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0005_category_subcategory'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userdetails',
            old_name='name',
            new_name='username',
        ),
    ]
