# Generated by Django 4.1 on 2024-05-04 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0006_rename_name_userdetails_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userdetails',
            old_name='username',
            new_name='name',
        ),
    ]
