# Generated by Django 4.1 on 2024-05-05 08:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0007_rename_username_userdetails_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=200)),
                ('Product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authapp.products')),
            ],
        ),
    ]
