# Generated by Django 4.1 on 2024-05-05 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0008_cart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='Product_id',
            field=models.IntegerField(max_length=200),
        ),
    ]
