# Generated by Django 4.1 on 2024-05-07 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0010_products_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='quantity',
            field=models.IntegerField(default=1, max_length=200),
        ),
        migrations.AlterField(
            model_name='products',
            name='product_image',
            field=models.ImageField(default='null', upload_to='product_images'),
        ),
    ]
