# Generated by Django 4.1 on 2024-05-13 06:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('authapp', '0012_alter_products_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='Product_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authapp.products'),
        ),
        migrations.AlterField(
            model_name='cart',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
